import type { Metadata } from "next";
import { Barlow, Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { ViewTransitions } from "next-view-transitions";
import { RootProvider } from "fumadocs-ui/provider/next";
import { cn } from "@/lib/utils";
import "katex/dist/katex.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const barlow = Barlow({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
  variable: "--font-barlow",
});
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");

  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body
          suppressHydrationWarning
          className={cn(
            "antialiased",
            geistSans.variable,
            geistMono.variable,
            barlow.variable,
            poppins.variable,
            barlow.className,
            theme?.value === "light" ? "light" : "dark"
          )}
        >
          <RootProvider
            theme={{
              enabled: false,
            }}
          >
            <div className="h-screen w-full">{children}</div>
          </RootProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
